spring.application.name=coupon

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
logging.level.org.hibernate.orm.jdbc.bind=TRACE

jwt.secret=${JWT_SECRET:change-me-in-prod-this-is-a-very-long-dev-secret-key-0123456789}
jwt.access-token-validity=3600000
jwt.refresh-token-validity=1209600000

app.seed.enabled=${SEED_ENABLED:true}
app.seed.admin-email=${ADMIN_EMAIL:admin@coupon.local}
app.seed.admin-password=${ADMIN_PASSWORD:admin1234}